name: Azure Static Web Apps CI/CD - dev

on:
  workflow_dispatch:

  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  # Build job
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run compile:dev
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build
  build_and_deploy_job:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MEADOW_0269C6E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          ###### NB: This makes only the deploy ######
          skip_app_build: true
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/build" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      - name: Print URL in PR
        uses: actions/github-script@v5
        with:
          script: |
            const url = steps.builddeploy.outputs.static_web_app_url; // Accessing the output from the Deploy step

            const issue_number = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const commentBody = `Website URL: ${url}`;
            await github.rest.issues.createComment({
              issue_number: issue_number,
              owner: owner,
              repo: repo,
              body: commentBody
            });
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MEADOW_0269C6E03 }}
          action: "close"
          app_location: "/"
